export * as authController from './auth.controller'
export * as chatController from './chat.controller'
export * as sourceController from './source.controller'
export * as categoryController from './category.controller'
export * as newsController from './news.controller'
